### ISSUE TITLE
Figure out return data type

### ISSUE THREAD

**Issue by achaikou** [equinor/vds-slice#16]
Do we always return user data as f4 little-endian?

Do we have any guarantee
1. that returned values from vds are floats (not ints or whatever else was possible in segy)
2. that is always f4, not f8 or some unknown float (which might be possible as openvds tool claims to lose no data)
3. what about endianess and do we care?
4. what does it all has to do with `enum class VolumeDataFormat` ?

Right now
- we return format for slice endpoint (metadata "format")
- return nothing for fence (it is supposed to be float, but is it always the same float or not? What if VolumeDataTraces are not float?).

**Comment by achaikou** [comment]
Currently the following seems to stand:

Openvds converts segy types to their own types described by enum VolumeDataFormat. At the moment though not all formats are supported. For example next ones give error

```
FIXED_POINT_WITH_GAIN_4_BYTE = 4 
IEEE_FLOAT_8_BYTE = 6
SIGNED_CHAR_3_BYTE = 7
SIGNED_INTEGER_8_BYTE = 9
UNSIGNED_INTEGER_8_BYTE = 12 
UNSIGNED_INTEGER_3_BYTE = 15
```

Thus we only can get R32, U8 and U16 values.

Correctness of conversions for `SIGNED_CHAR_1_BYTE = 8` and `SIGNED_SHORT_2_BYTE = 3` is questionable as data is not the same as it is in segy files.

Thus:
Slice always returns data in the format stored in vds metadata (which in conversion to numpy is f4, u1, u2). Fence always returns standard 4-byte float. Checked that if data was in u16 format, fence was still float.

As for the endianess, it looks like returned data will be of endiness of our server. Openvds seems to deal just fine with its own conversion part internally (though it was not tested due to lack of environment).
So as long as we host on little-endian, we send little-endian to the user.

**Comment by ErlendHaa** [comment]
Then let's go with numpy style format code!

**Comment by achaikou** [comment]
If I understand [this](https://community.opengroup.org/osdu/platform/domain-data-mgmt-services/seismic/open-vds/-/issues/156#note_165511) answer correctly, we should always request data as R32.

I've checked that requesting values written as U16/U8 as R32 returns correct results (at least in the spot-checks).
That seems to mean that all supported values should be requested as floats, regardless of the way they are written and what is in `layout->GetChannelFormat(0)`, and then parsed as numpy f4.

```
IBM_FLOAT_4_BYTE = 1
SIGNED_INTEGER_4_BYTE = 2
SIGNED_SHORT_2_BYTE = 3
IEEE_FLOAT_4_BYTE = 5
SIGNED_CHAR_1_BYTE = 8
UNSIGNED_INTEGER_4_BYTE = 10
UNSIGNED_SHORT_2_BYTE = 11
UNSIGNED_CHAR_1_BYTE = 16
```
