### ISSUE TITLE
Assert positive stepsize/axis values in datahandle

### ISSUE THREAD

**Issue by achaikou** [equinor/vds-slice#188]
- We suspect that current code will fail in several places if axes in the file do not have a positive stepsize.
- It can also happen that something breaks if our depth/time/annotation values are negative.
- We also not sure that files with negative stepsize/negative values even exist.

Thus in order to not implement something that might never be needed, just guard against it. (And implement it only later if someone comes to us complaining).

We'd need something like
`DataHandle: assert axis.min() >= 0 and assert axis.max() > axis.min() for each axis`

Note that the biggest problem here are test files, which we don't know how to make...

**Comment by yngve793** [comment]
According to Renaud Laurain negative stepsize should not exist.

**Comment by achaikou** [comment]
But values could be negative.

So we can just indefinitely postpone "negative stepsize check", but not indefinitely "make sure negative values are not spoiling anything"

**Comment by achaikou** [comment]
Per PO: almost all land data starts with minimal depth above the ground - so it would be negative.
So even if we throw now, we'll have to deal with it later anyway.
