### ISSUE TITLE
Clarify coordinate types in slice and fence

### ISSUE THREAD

**Issue by achaikou** [equinor/vds-slice#197]
For the moment
- in slice lineno and slice boundaries are ints. Coordinate system can be index or annotation
- in fence coordinates are floats. Coordinate system can be index, annotation or cdp.

In theory for index coordinate system floats make little sense (ints seem better), but for annotation it can happen that those are values in the file. It is not known though how often annotation coordinates are floats. It might be not worth of our attention.

It can also happen that someone explicitly wants data at index 1.4, wanting us to do some interpolation.

So we need to assure what we want floating values to mean in each case and if anything should be done with it.
For example does it make sense to expand slice lineno to floats and then interpolate/truncate to int/round to int/throw if that float lineno doesn't correspond to actual coordinate.

**Comment by yngve793** [comment]
Renaud Laurain clarified the use case here. 
- In fence a set of arbitrary coordinates are provided. Thus, these coordinates must be defined using float values. As a consequence return data will be interpolated. 
- For slice it is expected to get a subset of the points in the cube. As a result line number and boundaries can be provided as int without loosing functionality or precision. 

Renaud was happy with the current interface and did not request any change.
