### ISSUE TITLE
Add attributes for time/depth position of max, min and maxabs

### ISSUE THREAD

**Issue by achaikou** [equinor/vds-slice#198]
Introduce the following attributes:
```
max_at
min_at
maxabs_at
```
They are supposed to return respective depth/time value of the max, min and maxabs attributes.

In case there are several depth/times with the same value, we could return any, but it must be consistent on every call.

**Comment by AdilKhurshid** [comment]
@achaikou the positioning here is supposed to start from index 0 or 1?

**Comment by AdilKhurshid** [comment]
Got it, Thanks 🙌
