### ISSUE TITLE
Split core.go into logical subparts

### ISSUE THREAD

**Issue by yngve793** [equinor/vds-slice#215]
The file internal/core/core.go is getting close to 1k lines and contains several types of function definitions. The length and combination of functions makes it harder than it has to be to find the dependencies between functions. 
Candidates for separations can be: 
- Function calls directly related to API endpoint requests. 
- Attribute related functions
- Parallelisation of the attribute request
- More simple support functions

Currently it is unclear how the import of the c code bundle these functions.

**Comment by AdilKhurshid** [comment]
@achaikou I also want your opinion on how to split this file in a way that is easy to manage and understand. I completely agree with Yngve's point that the file is currently too long, and the code is hard to manage.

**Comment by achaikou** [comment]
I think the easiest way is to extract from core.go

```
core_slice.go  (439-534)
core_fence.go (534 - 598)
core_attributes.go (598 - end)
```

and leave everything else (like until line 439?) in core.go.
We can try to further extract something like core_models or core_conversions from there, but I don't see a point for now. But I am fine with further extracting if you think it makes code more readable :)

**Comment by yngve793** [comment]
Splitting it into 4 parts should be more than enough. 
Remember, this is just a suggestion from me and it does only make sense if the code actually gets better. 
Suggestions by Alena looks good to me, but a part of the job here is to make sure that the partitioning makes sense.
