### ISSUE TITLE
Add gtest for Fence and Slice in cppapi

### ISSUE THREAD

**Issue by yngve793** [equinor/vds-slice#222]
Attribute calculations have tests in tests/gtest/cppapi.cpp using a dummy vds file called SAMPLES_10. These tests ensures that c++ part of the code for each endpoint functions as expected. For completeness it would be nice to add similar tests for the fence and slice in cppapi.hpp. 

We should also consider to extend these tests to cover the metadata calls.

**Comment by achaikou** [comment]
Test suite extended significantly in #261
