### ISSUE TITLE
Scan docker image with Snyk and potentially include Snyk in GH actions

### ISSUE THREAD

**Issue by sveinung-r** [equinor/vds-slice#224]

**Comment by ajaust** [comment]
Some links for reference

- https://appsec.equinor.com/snyk/curriculum/2-integrations/
- https://docs.snyk.io/integrations/snyk-ci-cd-integrations/github-actions-integration/snyk-docker-action
- https://docs.snyk.io/integrations/git-repository-scm-integrations/snyk-github-integration
- https://docs.snyk.io/integrations/snyk-ci-cd-integrations/github-actions-integration
