### ISSUE TITLE
Rename vds-slice -> oneseismic 

### ISSUE THREAD

**Issue by sveinung-r** [equinor/vds-slice#225]
Archive old oneseismic repo.
(before archiving we might have to apply SCM policy there as well)

**Comment by yngve793** [comment]
PR with updated SCM policy made to the old oneseismic.

**Comment by achaikou** [comment]
Keep in mind that old oneseismic is distributed via pip under the oneseismic name and is included into some toolsets. We might need to think about consequences of renaming then.
