### ISSUE TITLE
Interpolating with fillValue at boundaries

### ISSUE THREAD

**Issue by sveinung-r** [equinor/vds-slice#230]
It has been reported that our API interpolates using fillValue at the boundaries. If that is the case this is a bug and should be fixed.

**Comment by achaikou** [comment]
It seems like something else caused the effects described in the issue.

It is openvds internal algorithms that are responsible for interpolation in horizontal plane, not us.

- For fence we retrieve with openvds all the values wanted by user and later overwrite values, which fall outside, with fillvalues. No interpolation is involved from our side.

- For attributes we do not retrieve traces marked with fill value. Fillvalue is inserted later in the correct place as a result of computation. All interpolation on our side happens on the real retrieved data, in vertical plane.

Local tests on synthetic data also did not detect any abnormality.

1. Note that we allow to return data 0.5 stepsize outside the bounds. In this case we rely on openvds extrapolation algorithms, whatever they do. PO doesn't see need for this behavior to change.

2. Note that we are not using NoValue openvds feature, which is responsible for filtering out bad data during the interpolation stage.
