### ISSUE TITLE
Define MetadataHandle for DoubleDatasource

### ISSUE THREAD

**Issue by yngve793** [equinor/vds-slice#235]
Metadata is defined for a single VDS file with functions:
- iline, 
- xline,
- samples, 
- get_axis
- BoundingBox
- src
- input_filename
- import_time_stamp
- coordinate_transformer
- get_layout

How do we define Metadata for the difference between two cubes?
For some of these it is trivial due to limitations required by the difference function. For other it is not so clear.

**Comment by achaikou** [comment]
Implemented in #261 .
