### ISSUE TITLE
Test reading Cache on expired sas token

### ISSUE THREAD

**Issue by yngve793** [equinor/vds-slice#241]
We are currently storing previous computed results in cache. It would be useful to test the following after an initial request:
- Verify that a new request with valid SAS token is read from cache
- Verify that a new request with invalid SAS token is ignored and no data is returned
- Verify that a new request with no SAS token is ignored and no data is returned

**Comment by achaikou** [comment]
Why shouldn't we be able to access cache results after initial token has expired?? Doesn't it defeat the purpose?

sas-tokens are not included in cache and have nothing to do with it.
We want short-lived sas tokens (like 1 minute) and long-lived cache which is accessible as long as user has a new shiny sas token currently valid for actual data.

**Comment by yngve793** [comment]
Bad formulation, issue rephrased.

**Comment by AdilKhurshid** [comment]
I have verified all the points mentioned in the task, and they are all working as we are expecting. We can now close this issue 😊

**Comment by yngve793** [comment]
Ok, that is fine by me.
