### ISSUE TITLE
Clarify our expectations to the input VDS

### ISSUE THREAD

**Issue by ErlendHaa** [equinor/vds-slice#63]
VDS files comes in many forms and shapes. However, our server is designed specifically for seismic. With that comes a some assumptions on how the VDS files we accept should look like. E.g w.r.t. to dimensionality and metadata. 

What we are currently expecting from the input VDS:

- N-dimensions = 3
- Dimension order = Depth/Time/Sample , crossline, inline.
- Annotations are defined
- Coordinate transform (origin, inline step, crossline step) is defined

We should evaluate if there are more expectations we should / make. Generally I would say it's a good thing to start out a bit to0 strict and then loosen up as we see the need. The basic assumptions we make should perhaps be documented in the README and possibly the Swagger docs

**Comment by ajaust** [comment]
I think if we want to be strict we could also think about restrictions/expectations regarding the following points:

- Do we have expectations regarding the number of [channels](https://osdu.pages.opengroup.org/platform/domain-data-mgmt-services/seismic/open-vds/vds/deepdive/deepdive.html#channels-and-data-type), their order and content? Or more general, what is the [anatomy of the VDS](https://osdu.pages.opengroup.org/platform/domain-data-mgmt-services/seismic/open-vds/vds/deepdive/deepdive.html#example-anatomy-of-a-vds) what we expect?
  - [SEGYImport](https://osdu.pages.opengroup.org/platform/domain-data-mgmt-services/seismic/open-vds/tools/SEGYImport/README.html) creates three channels by default containing the cube data, SEGY trace headers and a trace mask channel.
  - Would fast slices be allowed?
- [Compression](https://osdu.pages.opengroup.org/platform/domain-data-mgmt-services/seismic/open-vds/vds/deepdive/deepdive.html#compression-format-and-quality). Do we allow it?
- [Level of detail](https://osdu.pages.opengroup.org/platform/domain-data-mgmt-services/seismic/open-vds/vds/deepdive/deepdive.html#level-of-detail-lod) (LOD). Do we allow/expect several LODs? 
  - This could affect the decision on expected [margins](https://osdu.pages.opengroup.org/platform/domain-data-mgmt-services/seismic/open-vds/vds/deepdive/deepdive.html#margin-size). Do we require the margin to be zero if we expect now LODs?
- [Brick size](https://osdu.pages.opengroup.org/platform/domain-data-mgmt-services/seismic/open-vds/vds/deepdive/deepdive.html#brick-size). Do we require to the use of the default of uncompressed files?
- What do we expect regarding metadata?
  - Import information metadata. Do we require a reference to the original file?
  - Coordinate reference system in well-known text format (`crs-wkt`). I guess we should require a coordinate system identifier.
  - OpenVDS specifies some [expectations](https://osdu.pages.opengroup.org/platform/domain-data-mgmt-services/seismic/open-vds/vds/deepdive/deepdive.html#metadata) of metadata that should be present for seismic data.

**Comment by achaikou** [comment]
Assumptions:
- cdpx/cdpy are defined in the segy file and thus in vds
- data spacing is regular in all directions
- data can always be read as R32 without losing meaningful quality
- everything was imported with some default expected endianess (there is some --little-endian param in SEGYImport, unsure what it means and if that in any way affects us)
