### ISSUE TITLE
Create base image with OpenVDS installed

### ISSUE THREAD

**Issue by ErlendHaa** [equinor/vds-slice#73]
Too save on recompilation both for development and CI

**Comment by achaikou** [comment]
Image and solution for manual E2E tests run is waiting for approval in PR https://github.com/equinor/vds-slice/pull/53 

There we already discussed what our options are and decided they are not many.

As we don't want to publish openvds in dockerhub as our own public image, we need to use Azure Container Registry.
To access it in Dockerfile, we first have to download it from ACR.
ACR is protected, meaning we need credentials.
And in Github actions secrets are not passed to PRs triggered from forks.

As we didn't want to create a public service principal to give access to this ACR and don't want to publish openvds, it is not clear what else are our options and how exactly we can save on recompilation for development and CI.

**Comment by achaikou** [comment]
Solved instead by introducing cache #89
